# This is a basic workflow to support move from SAS 9.4 Enterprise Guide to SAS Viya studio flows

name: Automate move of Enterprise Guide to SAS Viya

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Setting up a workflow to prepare-target, import content, and validate content on the target environment
jobs:
  # This workflow contains 1 main job
  move2viya:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: prepare-target
        run: |
          echo Preparing target environment
          echo test, and deploy your project.

      # Runs a set of commands using the runners shell
      - name: import
        run: |
          echo Import EG project to SAS Viya from the git repo
          echo test, and deploy your project.

      - name: validate
        run: |
          echo Validate what we just imported
          echo test, and deploy your project.

