# This is a basic workflow to support move from SAS 9.4 Enterprise Guide to SAS Viya studio flows

name: Automate move of Enterprise Guide to SAS Viya

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Setting up a workflow to prepare-target, import content, and validate content on the target environment
jobs:
  # This workflow contains 1 main job
  move2viya:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: cleanup-target
        run: |
          echo Preparing target environment
          sh PSGEL270-RACE/utilities/resetViya.sh ||  exit_code=$?
          if [ $exit_code -ne 0 ]; then echo $exit_code; fi;

      - name: prepare-target
        run: |
          echo Preparing target environment
          export SAS_CLI_PROFILE=${current_namespace}
          export SSL_CERT_FILE=~/.certs/${current_namespace}_trustedcerts.pem
          export REQUESTS_CA_BUNDLE=${SSL_CERT_FILE}
          /opt/pyviyatools/loginviauthinfo.py
          # setup startup and autoexec for compute, batch and sas studio
          echo "Configure startup and autoexec for compute and batch as well as fileshare in sas studio"
          sas-viya configuration configurations update --file PSGEL270-RACE/config/compute-startup_commands.json
          sas-viya configuration configurations update --file PSGEL270-RACE/config/compute-autoexec.json
          sas-viya configuration configurations update --file PSGEL270-RACE/config/batch-autoexec.json
          sas-viya configuration configurations update --file PSGEL270-RACE/config/update_studio.json

      # Runs a set of commands using the runners shell
      - name: import
        run: |
          echo Import EG project to SAS Viya from the git repo
          echo test, and deploy your project.

      - name: validate
        run: |
          echo Validate what we just imported
          echo test, and deploy your project.

